#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
session-summary 技能自测：逐项验证 extract-session.py 的抽取模式、过滤规则、
会话定位与退出码分支。

**改过 `scripts/extract-session.py` 必须重跑本脚本**。其中两条用例锚定历史回归
（曾因实际使用暴露并修复的缺陷，防止复发）：
  C02 ← c788e2b（--user 模式漏抽技能命令发起的用户输入）
  C11 ← db6bd0f（timeline 模式斜杠命令用户消息被整条丢弃）

隔离性：全部用例在系统临时目录里构造**合成**会话记录（.jsonl），不读取也不触碰
真实会话；定位类用例（C13）通过临时 HOME / USERPROFILE 指向假 projects 目录，
不依赖本机真实 `~/.claude/projects`。

用法:
    python selftest.py        # 跑全部用例，逐项打印 PASS / FAIL / ERROR
退出码: 0 = 无 FAIL / ERROR；1 = 有失败项
"""
import os
import re
import json
import shutil
import subprocess
import sys
import tempfile
import codecs
import traceback

# Windows 控制台缺省 GBK，强制 UTF-8 输出（同仓库其他脚本的处理）。
def _ensure_utf8():
    for name in ("stdout", "stderr"):
        stream = getattr(sys, name, None)
        if stream is None:
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="backslashreplace")
            continue
        except Exception:
            pass
        try:
            buf = getattr(stream, "buffer", None)
            if buf is not None and hasattr(stream, "write"):
                setattr(sys, name, codecs.getwriter("utf-8")(buf, errors="backslashreplace"))
        except Exception:
            pass


_ensure_utf8()

# 自定位被测脚本（技能目录自包含，不依赖仓库位置与盘符）。
HERE = os.path.dirname(os.path.abspath(__file__))
EXE = os.path.join(HERE, "extract-session.py")
PY = sys.executable

RESULTS = []


def run(args, cwd=None, home=None):
    """跑被测脚本；home 时把 HOME / USERPROFILE 一并指向假主目录（定位类用例）。"""
    env = dict(os.environ)
    if home:
        env["HOME"] = home
        env["USERPROFILE"] = home
    return subprocess.run([PY, EXE] + list(args), cwd=cwd, capture_output=True,
                          encoding="utf-8", errors="replace", env=env)


def urec(text=None, ts="2026-09-22T10:00:00.000Z", meta=False, content=None):
    """合成 user 记录：content 缺省为纯文本；给 list 时按原样塞进 message.content。"""
    rec = {"type": "user", "timestamp": ts, "message": {"role": "user",
            "content": content if content is not None else text}}
    if meta:
        rec["isMeta"] = True
    return rec


def arec(blocks=None, ts="2026-09-22T10:00:01.000Z", sidechain=False):
    """合成 assistant 记录：blocks 为 content 列表（text / thinking / tool_use）。"""
    rec = {"type": "assistant", "timestamp": ts,
           "message": {"role": "assistant", "content": blocks or []}}
    if sidechain:
        rec["isSidechain"] = True
    return rec


def write_session(records, d, name="s.jsonl"):
    path = os.path.join(d, name)
    with open(path, "w", encoding="utf-8") as f:
        for r in records:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    return path


def check(cond, msg):
    if not cond:
        raise AssertionError(msg)


def wrap_case(fn):
    RESULTS.append(fn)
    return fn


@wrap_case
def C01_user基础抽取():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("第一句用户输入"), urec("第二句用户输入", ts="2026-09-22T11:00:00.000Z")], d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("第一句用户输入" in r.stdout and "第二句用户输入" in r.stdout, "两条消息未都抽出: %s" % r.stdout)
        check("### 2026-09-22T11:00:00.000Z" in r.stdout, "时间戳未按原样输出")
        check("[user] 2 条用户消息" in r.stdout, "统计行缺失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C02_斜杠命令参数解包_回归c788e2b():
    # 回归锚点 c788e2b：技能命令包装的用户输入必须解包出 <command-args> 的参数，
    # 不能整条漏抽、也不能把包装原文当用户消息。
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        wrapped = ("<command-message>feature-dev</command-message>\n"
                   "<command-name>/feature-dev</command-name>\n"
                   "<command-args>修复登录超时</command-args>\n")
        p = write_session([urec(wrapped)], d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 0, "退出码 %s，输出 %s" % (r.returncode, r.stdout))
        check("修复登录超时" in r.stdout, "命令参数未抽出: %s" % r.stdout)
        check("<command-name>" not in r.stdout and "<command-args>" not in r.stdout,
              "包装原文泄漏进输出: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C03_斜杠命令无参数整条丢弃():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("<command-message>skill</command-message>\n<command-name>/skill</command-name>")], d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 1, "无参数包装应导致无可抽取（退出 1），实际 %s" % r.returncode)
        check("没有可抽取" in r.stdout, "阻塞提示缺失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C04_Caveat与meta过滤():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [urec("Caveat: The messages below were generated by the user while running local commands."),
                urec("正常消息", meta=True),
                urec("可见消息")]
        p = write_session(recs, d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("Caveat:" not in r.stdout and "正常消息" not in r.stdout, "Caveat / meta 未过滤: %s" % r.stdout)
        check("可见消息" in r.stdout and "[user] 1 条用户消息" in r.stdout, "统计错误: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C05_tool_result回传不算用户输入():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        tool_back = [{"type": "tool_result",
                      "content": [{"type": "text", "text": "命令输出行"}]}]
        p = write_session([urec(content=tool_back), urec("真人输入")], d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("命令输出行" not in r.stdout, "tool_result 被当作用户输入: %s" % r.stdout)
        check("[user] 1 条用户消息" in r.stdout, "统计错误: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C06_压缩摘要默认过滤并提示():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [urec("This session is being continued in a new context. 之前的内容已压缩。"),
                urec("保留的用户消息")]
        p = write_session(recs, d)
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("This session is being continued" not in r.stdout, "压缩摘要未被过滤: %s" % r.stdout)
        check("已过滤 1 条上下文压缩摘要" in r.stdout, "过滤提示缺失: %s" % r.stdout)
        check("保留的用户消息" in r.stdout, "正常消息丢失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C07_with_summary保留摘要且口径正确():
    # --with-summary 时摘要被保留，统计口径应为「含 N 条」而非自相矛盾的「已过滤 N 条」。
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [urec("This session is being resumed after a context compaction. 之前的内容已压缩。"),
                urec("保留的用户消息")]
        p = write_session(recs, d)
        r = run([p, "--user", "--with-summary", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("This session is being resumed" in r.stdout, "--with-summary 未保留摘要: %s" % r.stdout)
        check("含 1 条上下文压缩摘要" in r.stdout, "保留口径提示缺失: %s" % r.stdout)
        check("已过滤" not in r.stdout, "保留时仍报「已过滤」，口径自相矛盾: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C08_limit截断标注():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("x" * 100)], d)
        r = run([p, "--user", "--limit", "10", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check(" ...[共 100 字]" in r.stdout, "截断标注缺失: %s" % r.stdout)
        check("x" * 11 not in r.stdout, "超出 limit 的文本未被截断: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C09_assistant尾部N条():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [arec([{"type": "text", "text": "结论%d" % i}]) for i in range(1, 6)]
        p = write_session(recs, d)
        r = run([p, "--assistant", "2", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("assistant 文本消息共 5 条，取尾部 2 条" in r.stdout, "头部统计缺失: %s" % r.stdout)
        check("结论4" in r.stdout and "结论5" in r.stdout, "尾部 2 条未抽出: %s" % r.stdout)
        check("结论1" not in r.stdout, "尾部截取失效: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C10_timeline基础渲染与计数():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [urec("时间线用户消息"),
                arec([{"type": "text", "text": "处理中"},
                      {"type": "tool_use", "name": "Edit",
                       "input": {"file_path": "some/long/path/foo.py", "old_string": "a", "new_string": "b"}}])]
        p = write_session(recs, d)
        r = run([p, "--timeline", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("@@@" in r.stdout and "时间线用户消息" in r.stdout, "用户行缺失: %s" % r.stdout)
        check(">>Edit[" in r.stdout and "foo.py" in r.stdout, "工具行或文件名缺失: %s" % r.stdout)
        check("long/path" not in r.stdout, "Edit 行应只留 basename: %s" % r.stdout)
        check("用户 1 条 / assistant 文本 1 条 / 工具调用 1 次" in r.stdout, "统计行不符: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C11_timeline保留斜杠命令_回归db6bd0f():
    # 回归锚点 db6bd0f：timeline 模式下技能命令包装的用户消息不能被整条丢弃。
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        wrapped = ("<command-message>feature-dev</command-message>\n"
                   "<command-name>/feature-dev</command-name>\n"
                   "<command-args>深度优化技能</command-args>\n")
        p = write_session([urec(wrapped)], d)
        r = run([p, "--timeline", "--stdout"])
        check(r.returncode == 0, "退出码 %s，输出 %s" % (r.returncode, r.stdout))
        check("深度优化技能" in r.stdout, "斜杠命令用户消息被丢弃: %s" % r.stdout)
        check("[USER" in r.stdout and "用户 1 条" in r.stdout, "统计错误: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C12_transcript各块标记():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        recs = [{"type": "summary", "summary": "压缩续接摘要"},
                arec([{"type": "thinking", "thinking": "想一想"},
                      {"type": "tool_use", "name": "Bash", "input": {"command": "ls"}},
                      {"type": "text", "text": "结论"}]),
                urec(content=[{"type": "tool_result",
                               "content": [{"type": "text", "text": "输出行"}]}]),
                arec([{"type": "text", "text": "支线消息"}], sidechain=True),
                {"type": "queue-operation", "content": "排队操作"}]
        p = write_session(recs, d)
        r = run([p, "--transcript", "--stdout"])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        for mark in ("[SUMMARY] 压缩续接摘要", "[THINK]", "[TOOL_USE #1] Bash", "[TEXT] 结论",
                     "[TOOL_RESULT] 输出行", "<SIDECHAIN>"):
            check(mark in r.stdout, "标记 %r 缺失: %s" % (mark, r.stdout))
        check("记录 3 条 / 工具调用 1 次" in r.stdout, "统计不符（queue-operation 应跳过）: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C13_按id定位与路径转义():
    # 定位走 expanduser('~')，用假 HOME / USERPROFILE 指向临时目录；
    # 期望转义与实现同规则（非字母数字 → -），路径用例含空格与下划线以覆盖转义面。
    home = tempfile.mkdtemp(prefix="ss-home-")
    try:
        sid = "abc123def"
        project = os.path.join(home, "foo bar_baz")
        escaped = re.sub(r"[^A-Za-z0-9]", "-", os.path.abspath(project))
        proj_dir = os.path.join(home, ".claude", "projects", escaped)
        os.makedirs(proj_dir)
        write_session([urec("按 id 定位的消息")], proj_dir, name=sid + ".jsonl")
        r = run([sid, "--project", project, "--stdout"], home=home)
        check(r.returncode == 0, "定位失败（退出 %s）: %s" % (r.returncode, r.stdout))
        check("按 id 定位的消息" in r.stdout, "内容未抽出: %s" % r.stdout)
    finally:
        shutil.rmtree(home, ignore_errors=True)


@wrap_case
def C14_多模式互斥():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("x")], d)
        r = run([p, "--user", "--timeline", "--stdout"])
        check(r.returncode == 1, "多模式应退出 1，实际 %s" % r.returncode)
        check("一次只能指定一种模式" in r.stdout, "互斥提示缺失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C15_会话文件不可定位():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        r = run(["no-such-session-id", "--project", d, "--stdout"])
        check(r.returncode == 1, "不可定位应退出 1，实际 %s" % r.returncode)
        check("找不到会话文件" in r.stdout, "阻塞提示缺失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C16_无可抽取内容():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = os.path.join(d, "empty.jsonl")
        with open(p, "w", encoding="utf-8") as f:
            f.write("不是 JSON 的行\n\n")
        r = run([p, "--user", "--stdout"])
        check(r.returncode == 1, "无可抽取应退出 1，实际 %s" % r.returncode)
        check("没有可抽取" in r.stdout, "阻塞提示缺失: %s" % r.stdout)
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C17_自定义落盘路径():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("落盘内容")], d)
        out = os.path.join(d, "custom.md")
        r = run([p, "--user", "--out", out])
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        check("落盘:" in r.stdout, "落盘提示缺失: %s" % r.stdout)
        check(os.path.isfile(out), "落盘文件不存在")
        with open(out, encoding="utf-8") as f:
            check("落盘内容" in f.read(), "落盘文件内容缺失")
    finally:
        shutil.rmtree(d, ignore_errors=True)


@wrap_case
def C18_默认落盘到_tasks():
    d = tempfile.mkdtemp(prefix="ss-")
    try:
        p = write_session([urec("默认路径")], d)
        r = run([p, "--user"], cwd=d)
        check(r.returncode == 0, "退出码 %s" % r.returncode)
        expected = os.path.join(d, ".tasks", "session-extract", "s-user.md")
        check(os.path.isfile(expected), "默认落盘文件缺失: %s" % expected)
    finally:
        shutil.rmtree(d, ignore_errors=True)


def main():
    print("session-summary 自测：%d 个用例" % len(RESULTS))
    fail = 0
    for fn in RESULTS:
        name = fn.__name__
        try:
            fn()
            print("PASS  %s" % name)
        except AssertionError as e:
            fail += 1
            print("FAIL  %s —— %s" % (name, e))
        except Exception:
            fail += 1
            print("ERROR %s\n%s" % (name, traceback.format_exc()))
    print("\n结果: %d/%d 通过" % (len(RESULTS) - fail, len(RESULTS)))
    return 1 if fail else 0


if __name__ == "__main__":
    sys.exit(main())
